name: Docker Build and Push CI

on:
  workflow_run:
    workflows: ["Docker Build and Push Base Image"]
    branches: [main]
    types:
      - completed

env:
  IMAGE_NAME: dwinks/rattler433

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
            path: 'config.json'
            prop_path: 'version'
      - run: echo ${{steps.version.outputs.prop}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386

      - name: Build the Docker image
        run: docker buildx build . --file Dockerfile --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386 --tag $IMAGE_NAME:${{steps.version.outputs.prop}} --push
