name: Docker Build and Push Base Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile.base'
  schedule:
    - cron: "0 0 * * *"

env:
  IMAGE_NAME: dwinks/rattler433-base

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386

      - name: Build the Docker image
        run: docker buildx build . --file Dockerfile.base --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386 --tag $IMAGE_NAME:latest --push
